# Generated by Django 4.1.3 on 2023-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurants_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
