# Generated by Django 4.1.3 on 2023-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurants_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.ImageField(default='ubereats/logos/default_logo.jpg', upload_to='ubereats/logos/'),
        ),
    ]
