# Generated by Django 4.1.3 on 2023-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitems_options_alter_orders_options_and_more'),
        ('restaurants', '0006_alter_restaurants_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restaurants',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='logo',
            field=models.ImageField(
                default='/default_logo.jpg', upload_to='logos/'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='restaurants',
            table='restaurants',
        ),
    ]
