# Generated by Django 4.1.3 on 2023-06-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='reviews',
        ),
    ]
