# Generated by Django 4.1.3 on 2023-06-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
