version: "3.9"

services:
  backend:
    build: ./backend
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/uber_eats_backend/:/code/
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
