# Generated by Django 4.1.3 on 2023-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_finished_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
