version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'food_dasher'
      MYSQL_USER: 'hanklin'
      MYSQL_PASSWORD: 'hanklin'
      MYSQL_ROOT_PASSWORD: 'mitlab123456'
    ports:
      - '33336:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '30888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'hanklin'
